version: '3.8'

services:
  mongoservice:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  ui:
    image: taleemhelp/ui:0.0
    container_name: taleemhelp_ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    
  api:
    image: taleemhelp/api:0.0
    container_name: taleemhelp_api
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongoservice:27017/taleem_db
      JWT_SECRET: "sadkjf3o7845nmWzveGrjHhq3iu4y6Q2cfujfqbi7Xou2Hvq"
    ports:
      - "5000:5000"
    depends_on:
      - mongoservice

volumes:
  mongodb-data:
