version: '3.8'

services:
  mongoservice:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db


volumes:
  mongodb-data:
# sudo docker-compose -f single-local-mongo.yml up -d
